### ISSUE TITLE
NDS controls messed up on recent minUI

### ISSUE THREAD

**Issue by dleicht** [ryanmsartor/RGXX-Custom-MinUI-Paks#2]
Hey Ryan, thanks for your work here.

I'm seeing a strange bug with your DS.pak on the latest MinUI (20240817-2).
Drastic does start and load games, but the controls are messed up. ABXY don't do anything, unless switched to stylus mode. R1 will open the drastic menu, but since ABXY don't work i can't change any options there. START and SELECT will change the screen layout and orientation. It's a bit of a mess.

It's a bit weird, because as per your launch.sh it should just run drastic the same way as stock does it. My guess is that maybe shaun changed something with the control mapping in the latest minUI release.

Maybe you find the time to look into it.

Cheer, Dom

**Comment by ryanmsartor** [comment]
Hey Dom, thanks for reporting this. Mind if I get a little more info from you?

1) Which device are you using?
2) Which stock firmware version are you using underneath MinUI?
3) If you use the tool to reboot into stock, do you encounter the same control issues with DS?
4) Did this previously work for you using an older version of either the stock firmware or MinUI? And if so, do you recall which version you used last?

thanks!

**Comment by dleicht** [comment]
Hi

1. RG35XXSP
2. 1.0.5
3. No. After rebooting into stock, DS emulation works as it should, especially the controls are setup correctly. This issue only appears while booted into minUI.
4. Didn’t use any other versions of stock or minUI, so i can’t tell.

**Comment by ryanmsartor** [comment]
Hey again Dom, I finally got a chance to look into this issue further. It seems Shaun of MinUI had made some little control handling tweaks that inadvertently broke the controls on this extra DS pak. Thankfully he gave me a little direction on how I might fix it too!

All you need to do is add `export LD_LIBRARY_PATH="/usr/lib:$LD_LIBRARY_PATH"` somewhere above line 22 where the if-else-fi statement starts. Try it out and let me know if this fix works for you! If so, I'll add it to my next release and try to get it out there soon.

**Comment by dleicht** [comment]
Hi,
okay so i just tried that and unfortunately it didn't change anything.
Just to make sure we are on the same page here: which versions of stock OS and minUI are you running your NDS.pak on without issues?

**Comment by BrianMetallaoui** [comment]
To add more details to this. 

1. RG40XX H
2. RG40XX H-V1.0.3-EN64GB-240822 (latest at time of writing) on MinUI-20240908-0
3. Stock DS works great
4. Only have used this version 

I added `export LD_LIBRARY_PATH="/usr/lib:$LD_LIBRARY_PATH` but that did not change anything.
All the buttons seems to be there every scrambled like VOL+ is also the A button and L1 is Start

**Comment by haysidney** [comment]
Also running into this issue with scrambled buttons in drastic. RG35XXSP Stock OS 1.0.7. MinUI MinUI-20240924-2. Both are the latest versions as far as I'm aware. I applied commit 70edda92ba99b7045d92fef9c585b4ab35cd39cd (the LD_LIBRARY_PATH thing) and I still have the issue.

**Comment by haysidney** [comment]
Okay, I tinkered and changed the line from the commit I linked to above to the following:
`export LD_LIBRARY_PATH="/usr/lib32:/usr/lib:$LD_LIBRARY_PATH"`

Now the controls are working properly for me. ^^

Thank you again for all your hard work!

**Comment by BrianMetallaoui** [comment]
Can confirm it is working on my RG40XX H. Thanks you to both

**Comment by kurtmorris** [comment]
Can also confirm this fixed the issue on my RG40XX V, Thank you all.
